### ISSUE TITLE
"Activate" Error with 1.0.8 Pre

### ISSUE THREAD

**Issue by craigeley** [ttscoff/doing#67]
When I install and run the `--pre` version, I always get the same error on Ruby 2.0.0:

/Library/Ruby/Site/2.0.0/rubygems.rb:198:in `rescue in try_activate': undefined method `activate' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Site/2.0.0/rubygems.rb:195:in `try_activate'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/doing-1.0.8pre/bin/doing:3:in `<top (required)>'
	from /usr/bin/doing:23:in `load'
	from /usr/bin/doing:23:in `<main>'

This is when running any command: `config`, `now`, etc.

**Comment by ttscoff** [comment]
did you `bundle install`?

**Comment by craigeley** [comment]
No—just did `sudo gem install doing --pre`

**Comment by ttscoff** [comment]
What os are you on? I don't test on anything but OS X and Ruby 2+ these days, so I have limited knowledge of Ruby behavior outside of Darwin…

**Comment by craigeley** [comment]
Hmm, same for me. This is system Ruby 2.0.0 on the 10.10.3 beta. If I'm the only one seeing this is must be something on my end, but stable version installs fine, which is why I opened the issue.

**Comment by ttscoff** [comment]
Interesting. You might try moving your ~/.doingrc file and seeing if it's a
configuration issue.

**Comment by craigeley** [comment]
Uninstalled stable release, trashed the .doingrc file, same results. ¯\_(ツ)_/¯

**Comment by ttscoff** [comment]
Sorry about that. I wish the error was a bit more descriptive. It's 
referencing the point where the user home folder is set, but that call 
works fine on my 10.10.3 install, using Ruby 1.8, 1.9, 2.0, and 2.1 via 
rvm.

-Brett

**Comment by yasuhito** [comment]
Hi, I created a PR that fixes this issue. The fix is to add `lib/` to $LOAD_PATH so that `lib/doing.rb` can be found from `bin/doing`.

**Comment by ttscoff** [comment]
Thanks!
