### ISSUE TITLE
autotag issue

### ISSUE THREAD

**Issue by donalmacanri** [ttscoff/doing#55]
I can't execute any commands that add any entries to my doing file since upgrading to 1.08.

```
> GLI_DEBUG=true doing done -b "11.15am" -t "35m" Doing something
error: undefined method `each' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/doing-1.0.8pre/lib/doing/wwid.rb:1256:in `autotag': undefined method `each' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/doing-1.0.8pre/lib/doing/wwid.rb:351:in `add_item'
from /Library/Ruby/Gems/2.0.0/gems/doing-1.0.8pre/bin/doing:355:in `block (2 levels) in <top (required)>'
from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/command_support.rb:121:in `call'
from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/command_support.rb:121:in `execute'
from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/app_support.rb:284:in `block in call_command'
from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/app_support.rb:297:in `call'
from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/app_support.rb:297:in `call_command'
from /Library/Ruby/Gems/2.0.0/gems/gli-2.9.0/lib/gli/app_support.rb:79:in `run'
from /Library/Ruby/Gems/2.0.0/gems/doing-1.0.8pre/bin/doing:1058:in `<top (required)>'
from /usr/bin/doing:23:in `load'
from /usr/bin/doing:23:in `<main>'
```

Seems to be related to the auto tag functionality, because when I add the following to my ~/.doingrc file, things work again:

```
autotag:
    whitelist: []
    synonyms: []
```
